Activity_Subject__c,Activity_Type__c,Due_Date__c,Name
Maintain Contact,Other,30,Account_Customer
Follow-up with prospect,Call,3,Account_HotProspect
Premium Overdue,Call,7,Policy_OverduePremium
Dishonour Autopay,Call,5,Transaction_DishonorAutoPay
Birthday,Other,7,Account_Birthday
Policy Anniversary,Other,30,Policy_Anniversary
Follow-up UN,Other,3,Case_Underwriting
Follow-up lead,Call,15,Lead_HighRating
Opt-in Consent Required,Other,15,Account_Consent
Premium due,Call,15,Policy_PremiumDue
New Product Interest Selected,Call,15,Opportunity_NewProduct
IARB licence renewal,Other,30,Contact_IARBRenewal
New Policy Change,Other,3,Transaction_PolicyChange
Policy lapsed,Call,5,Policy_Lapse
New Lead Assigned,Other,5,Lead_Assignment
New Policy Assignment,Service,1,Policy_Policy_Assignment
