FirstName,LastName,Chinese_name__c,PersonEmail,Phone,PersonMobilePhone,Other_phone_number__c,Fax,Address_Line_1__c,Address_Line_2__c,Address_Line_3__c,Preferred_Channel__c,Preferred_Contact_Day__c,Preferred_Contact_Time__c,Gender__c,Marital_Status__c
Jamie,Oliver,米高鍾斯,jamie.oliver@axaiprooffice.demo,+852 1234 5678,+852 1234 1234,+852 1234 1234,+852 1234 1234,"One Pacific Place, 88 Queensway",Central,Hong Kong,1,2,3,M,S
Freddy,Cooper,鍾斯,freddie.cooper@axaiprooffice.demo,+852 1234 5678,+852 1234 1234,+852 1234 1234,+852 1234 1234,"One Pacific Place, 88 Queensway",Central,Hong Kong,1,2,3,M,S
